### ISSUE TITLE
After downloading the project

### ISSUE THREAD

**Issue by yassinzaid** [osamaabdulsattar/usersservice#9]
I have downloaded the project and it couldn't build, didn't recognize ( builder ) .

java: cannot find symbol
  symbol:   method builder()
  location: class com.example.usersservice.model.UserResource

![error](https://github.com/osamaabdulsattar/usersservice/assets/35197188/91154100-111e-4975-a4f8-4607bfd937bf)

**Comment by nagmalmusanif** [comment]
create new project sprint

**Comment by ahmedyahiaalkaff** [comment]
Try to add lombok plugin to your IDE, if using intellij try:
(File -> Settings -> Plugins) then search for lombok and install.

**Comment by yassinzaid** [comment]
@ahmedyahiaalkaff ... i did add it and the error disappeared  ..
